save_dir: ./saved_models
save_name: divideflex_noisy100
number_sample: 50
lambda_r: 0.005
noise_type: noisy100
noise_path: None
pre_epochs: 10
val_ratio: 0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 300000
num_eval_iter: 5000
num_labels: 5000
batch_size: 32
eval_batch_size: 32
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.001
momentum: 0.9
weight_decay: 0.0005
amp: True
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 8
alg: flexmatch
gpu: 0

